apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-devfile-gitlab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-devfile-gitlab
    app.kubernetes.io/part-of: python-test-devfile-gitlab
  name: python-devfile-gitlab
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: python-devfile-gitlab
status:
  loadBalancer: {}
